import {
  Code2,
  Rocket,
  Briefcase,
  Mail,
  Phone,
  Menu,
  X,
  Sun,
  Moon,
  ArrowRight,
  Check,
  Monitor,
  Gauge,
  Layers,
  LifeBuoy,
  ClipboardCheck,
  PenLine,
  Atom,
  LayoutGrid,
  FileCode2,
  Braces,
  Share2,
  Database,
  Wind,
  Palette,
  FileCode,
  Paintbrush,
  Cpu,
  Server,
  Droplets,
  Leaf,
  Building2,
  GitBranch,
  Container,
  Package,
  LayoutList,
  MousePointer2,
  Sparkles,
  ServerCog,
  CloudCog,
  TestTube2,
  Workflow,
  Bot,
  type LucideIcon,
  createLucideIcon,
} from 'lucide-react';
import {
  SiClaude,
  SiCss,
  SiCypress,
  SiCursor,
  SiDocker,
  SiDrupal,
  SiExpress,
  SiGit,
  SiHtml5,
  SiHubspot,
  SiJest,
  SiJira,
  SiJavascript,
  SiMake,
  SiMongodb,
  SiMysql,
  SiN8N,
  SiNestjs,
  SiNextdotjs,
  SiNodedotjs,
  SiPostgresql,
  SiPrisma,
  SiReact,
  SiReactquery,
  SiRedux,
  SiSass,
  SiTailwindcss,
  SiTestinglibrary,
  SiTypescript,
  SiVitest,
  SiWebpack,
  SiZapier,
} from 'react-icons/si';
import type { IconType } from 'react-icons/lib';

/** Lucide removed brand icons; built with lucide-react's createLucideIcon (stroke style). */
const Linkedin = createLucideIcon('Linkedin', [
  ['path', { d: 'M16 8a6 6 0 0 1 6 6v7h-4v-7a2 2 0 0 0-2-2 2 2 0 0 0-2 2v7h-4v-12h4v2', key: 'body' }],
  ['rect', { width: '4', height: '12', x: '2', y: '9', key: 'pillar' }],
  ['circle', { cx: '4', cy: '4', r: '2', key: 'head' }]
]);

export type IconName =
  | 'code' | 'rocket' | 'briefcase' | 'mail' | 'phone' | 'linkedin' | 'menu' | 'x' | 'sun' | 'moon' | 'arrow' | 'check'
  | 'monitor' | 'speed' | 'layers' | 'support' | 'audit' | 'design' | 'react' | 'next' | 'typescript'
  | 'javascript' | 'redux' | 'query' | 'tailwind' | 'sass' | 'html' | 'css' | 'node' | 'express'
  | 'drupal' | 'twig' | 'hybris' | 'git' | 'docker' | 'webpack' | 'jira' | 'cursor' | 'ai'
  | 'rest' | 'openai' | 'database' | 'prisma' | 'testing' | 'automation' | 'crm';

const icons: Record<IconName, LucideIcon> = {
  code: Code2,
  rocket: Rocket,
  briefcase: Briefcase,
  mail: Mail,
  phone: Phone,
  linkedin: Linkedin,
  menu: Menu,
  x: X,
  sun: Sun,
  moon: Moon,
  arrow: ArrowRight,
  check: Check,
  monitor: Monitor,
  speed: Gauge,
  layers: Layers,
  support: LifeBuoy,
  audit: ClipboardCheck,
  design: PenLine,
  react: Atom,
  next: LayoutGrid,
  typescript: FileCode2,
  javascript: Braces,
  redux: Share2,
  query: Database,
  tailwind: Wind,
  sass: Palette,
  html: FileCode,
  css: Paintbrush,
  node: Cpu,
  express: Server,
  drupal: Droplets,
  twig: Leaf,
  hybris: Building2,
  git: GitBranch,
  docker: Container,
  webpack: Package,
  jira: LayoutList,
  cursor: MousePointer2,
  ai: Sparkles,
  rest: ServerCog,
  openai: Bot,
  database: CloudCog,
  prisma: Database,
  testing: TestTube2,
  automation: Workflow,
  crm: Briefcase,
};

export const skillIconNames: Record<string, IconName> = {
  React: 'react',
  'Next.js': 'next',
  TypeScript: 'typescript',
  JavaScript: 'javascript',
  'Redux Toolkit': 'redux',
  'React Query': 'query',
  'Tailwind CSS': 'tailwind',
  Sass: 'sass',
  HTML5: 'html',
  CSS3: 'css',
  'Node.js': 'node',
  Express: 'express',
  NestJS: 'node',
  'REST APIs': 'rest',
  'OpenAI API': 'openai',
  PostgreSQL: 'database',
  MySQL: 'database',
  MongoDB: 'database',
  Prisma: 'prisma',
  Jest: 'testing',
  'React Testing Library': 'testing',
  Vitest: 'testing',
  Cypress: 'testing',
  Playwright: 'testing',
  n8n: 'automation',
  Make: 'automation',
  Zapier: 'automation',
  'HubSpot CRM': 'crm',
  Drupal: 'drupal',
  Twig: 'twig',
  Hybris: 'hybris',
  Git: 'git',
  Docker: 'docker',
  Webpack: 'webpack',
  Jira: 'jira',
  Cursor: 'cursor',
  'Claude AI': 'ai',
};

const skillBrandIcons: Record<string, { icon: IconType; color: string }> = {
  React: { icon: SiReact, color: '#61DAFB' },
  'Next.js': { icon: SiNextdotjs, color: 'currentColor' },
  TypeScript: { icon: SiTypescript, color: '#3178C6' },
  JavaScript: { icon: SiJavascript, color: '#F7DF1E' },
  'Redux Toolkit': { icon: SiRedux, color: '#764ABC' },
  'React Query': { icon: SiReactquery, color: '#FF4154' },
  'Tailwind CSS': { icon: SiTailwindcss, color: '#06B6D4' },
  Sass: { icon: SiSass, color: '#CC6699' },
  HTML5: { icon: SiHtml5, color: '#E34F26' },
  CSS3: { icon: SiCss, color: '#1572B6' },
  'Node.js': { icon: SiNodedotjs, color: '#5FA04E' },
  Express: { icon: SiExpress, color: 'currentColor' },
  NestJS: { icon: SiNestjs, color: '#E0234E' },
  PostgreSQL: { icon: SiPostgresql, color: '#4169E1' },
  MySQL: { icon: SiMysql, color: '#4479A1' },
  MongoDB: { icon: SiMongodb, color: '#47A248' },
  Prisma: { icon: SiPrisma, color: '#5A67D8' },
  Jest: { icon: SiJest, color: '#C21325' },
  'React Testing Library': { icon: SiTestinglibrary, color: '#E33332' },
  Vitest: { icon: SiVitest, color: '#FCC72B' },
  Cypress: { icon: SiCypress, color: '#69D3A7' },
  n8n: { icon: SiN8N, color: '#EA4B71' },
  Make: { icon: SiMake, color: '#6D00CC' },
  Zapier: { icon: SiZapier, color: '#FF4A00' },
  'HubSpot CRM': { icon: SiHubspot, color: '#FF7A59' },
  Drupal: { icon: SiDrupal, color: '#0678BE' },
  Git: { icon: SiGit, color: '#F05032' },
  Docker: { icon: SiDocker, color: '#2496ED' },
  Webpack: { icon: SiWebpack, color: '#8DD6F9' },
  Jira: { icon: SiJira, color: '#2684FF' },
  Cursor: { icon: SiCursor, color: 'currentColor' },
  'Claude AI': { icon: SiClaude, color: '#D97757' },
};

export function Icon({ name, className = '' }: { name: IconName; className?: string }) {
  const LucideIconComponent = icons[name];
  return <LucideIconComponent className={className} strokeWidth={1.9} aria-hidden="true" />;
}

export function SkillIcon({ skill, className = '' }: { skill: string; className?: string }) {
  const brand = skillBrandIcons[skill];
  if (brand) {
    const BrandIcon = brand.icon;
    const neutralClass = brand.color === 'currentColor' ? ' text-[#111318] dark:text-white' : '';
    return <BrandIcon className={`${className}${neutralClass}`} color={brand.color} aria-hidden="true" />;
  }

  return <Icon name={skillIconNames[skill]} className={`${className} text-[#d9ff63]`} />;
}
